ALTER TABLE customers MODIFY COLUMN billingStreet VARCHAR(60) NOT NULL;
ALTER TABLE customers MODIFY COLUMN billingCity VARCHAR(40) NOT NULL;
ALTER TABLE customers MODIFY COLUMN billingState VARCHAR(2) NOT NULL;
ALTER TABLE customers MODIFY COLUMN billingZipCode VARCHAR(10) NOT NULL;

ALTER TABLE customers MODIFY COLUMN billingStreet VARCHAR(60) NULL;
ALTER TABLE customers MODIFY COLUMN billingCity VARCHAR(40) NULL;
ALTER TABLE customers MODIFY COLUMN billingState VARCHAR(2) NULL;
ALTER TABLE customers MODIFY COLUMN billingZipCode VARCHAR(10) NULL;
