ALTER TABLE users ADD COLUMN status CHAR(1) NOT NULL AFTER phone;
ALTER TABLE users ADD COLUMN eFlag TINYINT(1) NOT NULL AFTER status;
ALTER TABLE users ADD COLUMN cFlag TINYINT(1) NOT NULL AFTER eFlag;
ALTER TABLE users ADD COLUMN created DATETIME NOT NULL AFTER cFlag;

ALTER TABLE customers MODIFY COLUMN billingStreet VARCHAR(60) NULL;
ALTER TABLE customers MODIFY COLUMN billingCity VARCHAR(40) NULL;
ALTER TABLE customers MODIFY COLUMN billingState VARCHAR(2) NULL;
ALTER TABLE customers MODIFY COLUMN billingZipCode VARCHAR(10) NULL;

ALTER TABLE locations ADD COLUMN status CHAR(1) NOT NULL AFTER managerID;
ALTER TABLE locations ADD COLUMN created DATETIME NOT NULL AFTER status;
ALTER TABLE locations ADD COLUMN createdBy INTEGER NULL AFTER created;

ALTER TABLE orders ADD COLUMN status CHAR(1) NOT NULL AFTER shippingZipCode;
ALTER TABLE orders ADD COLUMN created DATETIME NOT NULL AFTER status;
ALTER TABLE orders ADD COLUMN referBy INTEGER NULL AFTER created;

ALTER TABLE menuitems ADD COLUMN status CHAR(1) NOT NULL AFTER ranking;
ALTER TABLE menuitems ADD COLUMN created DATETIME NOT NULL AFTER status;
ALTER TABLE menuitems ADD COLUMN createdBy INTEGER NULL AFTER created;

ALTER TABLE orderlines ADD COLUMN status CHAR(1) NOT NULL AFTER quantity;

ALTER TABLE customers MODIFY COLUMN billingStreet VARCHAR(60) NOT NULL;
ALTER TABLE customers MODIFY COLUMN billingCity VARCHAR(40) NOT NULL;
ALTER TABLE customers MODIFY COLUMN billingState VARCHAR(2) NOT NULL;
ALTER TABLE customers MODIFY COLUMN billingZipCode VARCHAR(10) NOT NULL;


